[package]
name = "todomvc"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
serde = "1.0.106"
uuid = { version = "0.8.1", features = ["serde", "v4", "wasm-bindgen"] }
indexmap = { version = "1.3.2", features = ["serde-1"] }
enclose = "1.1.8"
