[package]
name = "todomvc"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
wasm-bindgen = "^0.2.45"
web-sys = "^0.3.22"

serde = { version = "^1.0.92", features = ['derive'] }
