[package]
name = "auth"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo-console = "0.2.3"
gloo-net = "0.2.6"
gloo-storage = "0.2.2"
seed = {path = "../../"}
serde = "1.0.152"
