[package]
name = "graphql"
version = "0.1.0"
authors = ["Martin Kavík <martin@kavik.cz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = {path = "../../"}
graphql_client = "0.10.0"
serde = "1.0.137"
itertools = "0.10.3"
