[package]
name = "client"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
seed = { path = "../../../" }
serde = "^1.0.90"
serde_derive = "^1.0.90"
serde_json = "^1.0.39"
wasm-bindgen = "^0.2.42"
web-sys = "^0.3.19"
futures = "0.1"

shared = { path = "../shared"}
