[package]
name = "fetch"
version = "0.1.0"
authors = ["TatriX <tatrics@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo-net = "0.2.6"
futures = "0.3.26"
seed = { path = "../../" }
serde = { version = "1.0.152", features = ["derive"] }
