[package]
name = "server"
version = "0.1.0"
authors = ["Your Name <email@address.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
actix-files = "0.1.1"

serde_json = "^1.0.39"

shared = { path = "../shared" }
