[package]
name = "websocket"
version = "0.1.0"
authors = ["Markus Kohlhase <markus.kohlhase@slowtec.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

# [dev-dependencies]
# wasm-bindgen-test = "0.3.18"

[dependencies]
# common
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
rmp-serde = "0.14.4"

# server
ws = { version = "0.9.1", optional = true }

#client
seed = { path = "../../", optional = true }

[features]
default = []
client = ["seed"]
server = ["ws"]

