[package]
name = "markdown"
version = "0.1.0"
authors = ["Florian Warzecha <liketechnik@disroot.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
pulldown-cmark = "0.8.0"

[dependencies]
seed = {path = "../../"}
